# Generated by Django 4.2.6 on 2023-10-19 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_is_active_usuario_is_admin_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informações',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renda_familiar', models.CharField(choices=[('R$ 0.0 - R$ 1.000.00', 'R$ 0.0 - R$ 1.000.00'), ('R$ 1.000.00 - R$ 5.000.00', 'R$ 1.000.00 - R$ 5.000.00'), ('R$ 5.000.00 - R$ 15.000.00', 'R$ 5.000.00 - R$ 15.000.00'), ('Maior que R$ 20.000.00', 'Maior que R$ 20.000.00')], max_length=100)),
                ('numero_membros_familia', models.CharField(choices=[('Até 5 Membros', 'Até 5 Membros'), ('Até 10 Membros', 'Até 10 Membros'), ('Mais que 10', 'Mais que 10')], max_length=100)),
                ('despesas_mensais', models.CharField(choices=[('R$ 0.0 - R$ 1.000.00', 'R$ 0.0 - R$ 1.000.00'), ('R$ 1.000.00 - R$ 5.000.00', 'R$ 1.000.00 - R$ 5.000.00'), ('R$ 5.000.00 - R$ 15.000.00', 'R$ 5.000.00 - R$ 15.000.00'), ('Maior que R$ 20.000.00', 'Maior que R$ 20.000.00')], max_length=100)),
                ('nivel_escolaridade', models.CharField(choices=[('Ensino Fundamental Incompleto', 'Ensino Fundamental Incompleto'), ('Ensino Médio Incompleto', 'Ensino Médio Incompleto'), ('Ensino Médio Completo', 'Ensino Médio Completo'), ('Cursando Faculdade', 'Cursando Faculdade'), ('Curso Superior Completo', 'Curso Superior Completo')], max_length=150)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('apartamento', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
