# Generated by Django 4.2.6 on 2023-10-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_informações_endereco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='apartamento',
            new_name='complemento',
        ),
    ]
