# Generated by Django 4.2.6 on 2023-10-21 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_apartamento_endereco_complemento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informações',
            old_name='renda_familiar',
            new_name='renda',
        ),
    ]
